// import { AntdRegistry } from "@ant-design/nextjs-registry";
"use client";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "@ant-design/v5-patch-for-react-19";
// // import "antd/dist/reset.css";
// // import "antd/dist/antd.css";

// import "./globals.css"; // your Tailwind CSS file

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <AntdRegistry>{children}</AntdRegistry>
//       </body>
//     </html>
//   );
// }
import React from "react";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "antd/dist/reset.css";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ReduxProviders } from "./ReduxProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";
const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <head>
      <link rel="icon" type="image/png" href="/logo/logo.png" />
      <link rel="apple-touch-icon" href="/logo/logo.png" />
    </head>
    <body>
      <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""}>
        <ReduxProviders>
          <Toaster
            position="top-center"
            toastOptions={{
              className: "app-toast",
              duration: 3500,
            }}
          />
          <AntdRegistry>{children}</AntdRegistry>
        </ReduxProviders>
      </GoogleOAuthProvider>
    </body>
  </html>
);

export default RootLayout;
